// Test program to generate test vectors for C++/Rust compatibility
// Tests basic signature aggregation

#include <iostream>
#include <iomanip>
#include <vector>
#include <string>
#include "bls.hpp"
#include "schemes.hpp"
#include "util.hpp"
#include "elements.hpp"

using namespace bls;
using namespace std;

void printHex(const string& label, const vector<uint8_t>& data) {
    cout << label << " = [";
    for (size_t i = 0; i < data.size(); i++) {
        if (i > 0) cout << ", ";
        cout << "0x" << setfill('0') << setw(2) << hex << (int)data[i];
    }
    cout << "];" << endl;
}

void printRustArray(const string& label, const vector<uint8_t>& data) {
    cout << label << " = [";
    for (size_t i = 0; i < data.size(); i++) {
        if (i > 0) cout << ", ";
        cout << (int)data[i] << "u8";
    }
    cout << "];" << endl;
}

int main() {
    cout << "// Test Vectors for C++/Rust Compatibility" << endl;
    cout << "// Generated by bls-signatures C++ implementation" << endl;
    cout << "// These are the raw values - coefficients must be computed separately" << endl;
    
    // Test Case 1: Three deterministic keys
    cout << "\n// Test Case 1: Three signers with deterministic keys" << endl;
    
    vector<PrivateKey> sks;
    vector<G1Element> pks;
    
    // Generate keys using seed [1,1,1...], [2,2,2...], [3,3,3...]
    cout << "\n// Private keys generated from seeds:" << endl;
    for (uint8_t i = 1; i <= 3; i++) {
        vector<uint8_t> seed(32, i);
        cout << "// Seed " << (int)i << ": [" << (int)i << ", " << (int)i << ", ...] (32 bytes)" << endl;
        PrivateKey sk = BasicSchemeMPL().KeyGen(seed);
        sks.push_back(sk);
        pks.push_back(sk.GetG1Element());
    }
    
    // Print public keys
    cout << "\n// Public keys (48 bytes each, G1 compressed):" << endl;
    for (size_t i = 0; i < pks.size(); i++) {
        auto pkBytes = pks[i].Serialize();
        printHex("let pk" + to_string(i+1) + "_bytes", pkBytes);
    }
    
    // Message
    vector<uint8_t> message = {0x74, 0x65, 0x73, 0x74, 0x20, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65}; // "test message"
    cout << "\n// Message: \"test message\"" << endl;
    printRustArray("let message", message);
    
    // Generate individual signatures
    cout << "\n// Individual signatures (96 bytes each, G2 compressed):" << endl;
    vector<G2Element> sigs;
    for (size_t i = 0; i < sks.size(); i++) {
        G2Element sig = BasicSchemeMPL().Sign(sks[i], message);
        sigs.push_back(sig);
        auto sigBytes = sig.Serialize();
        printHex("let sig" + to_string(i+1) + "_bytes", sigBytes);
    }
    
    // Aggregate signatures (without coefficients - just for reference)
    cout << "\n// Basic aggregated signature (no coefficients):" << endl;
    G2Element aggSig = BasicSchemeMPL().Aggregate(sigs);
    printHex("let agg_sig_basic", aggSig.Serialize());
    
    // Verify basic aggregation works
    bool basicVerify = BasicSchemeMPL().AggregateVerify(pks, vector<vector<uint8_t>>(pks.size(), message), aggSig);
    cout << "// Basic aggregate verify result: " << (basicVerify ? "true" : "false") << endl;
    
    // Test with different key orders
    cout << "\n// Test Case 2: Keys in reversed order" << endl;
    vector<G1Element> pksReversed = {pks[2], pks[1], pks[0]};
    vector<G2Element> sigsReversed = {sigs[2], sigs[1], sigs[0]};
    
    cout << "// Public keys in reversed order:" << endl;
    for (size_t i = 0; i < pksReversed.size(); i++) {
        auto pkBytes = pksReversed[i].Serialize();
        cout << "// pk_reversed[" << i << "] = pk" << (3-i) << endl;
    }
    
    G2Element aggSigReversed = BasicSchemeMPL().Aggregate(sigsReversed);
    printHex("let agg_sig_reversed", aggSigReversed.Serialize());
    
    // Also print some debug info
    cout << "\n// Debug: First 8 bytes of each public key for easy comparison:" << endl;
    for (size_t i = 0; i < pks.size(); i++) {
        auto pkBytes = pks[i].Serialize();
        cout << "// pk" << (i+1) << " first 8 bytes: ";
        for (size_t j = 0; j < 8 && j < pkBytes.size(); j++) {
            cout << setfill('0') << setw(2) << hex << (int)pkBytes[j] << " ";
        }
        cout << endl;
    }
    
    return 0;
}