// Full test vector generator for complete C++/Rust compatibility testing
// This generates all necessary data including private keys for exact reproduction

#include <iostream>
#include <iomanip>
#include <vector>
#include <string>
#include "bls.hpp"
#include "schemes.hpp"
#include "util.hpp"
#include "elements.hpp"

using namespace bls;
using namespace std;

void printHexArray(const string& name, const vector<uint8_t>& data) {
    cout << "const " << name << ": [u8; " << data.size() << "] = [";
    for (size_t i = 0; i < data.size(); i++) {
        if (i > 0) cout << ", ";
        cout << "0x" << setfill('0') << setw(2) << hex << (int)data[i];
    }
    cout << "];" << endl;
}

// Helper class to access protected methods
class TestCoreMPL : public CoreMPL {
public:
    TestCoreMPL() : CoreMPL("BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_NUL_") {}
    
    using CoreMPL::AggregateSecure;
    using CoreMPL::VerifySecure;
};

int main() {
    cout << "// Full Compatibility Test Vectors" << endl;
    cout << "// Generated by C++ bls-signatures implementation" << endl;
    cout << "// These vectors include private keys for exact reproduction" << endl;
    cout << endl;
    
    // Create deterministic private keys
    vector<uint8_t> sk1_bytes = {
        0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde, 0xf0,
        0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88,
        0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff, 0x00,
        0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08
    };
    
    vector<uint8_t> sk2_bytes = {
        0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0x01,
        0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99,
        0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff, 0x00, 0x11,
        0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19
    };
    
    vector<uint8_t> sk3_bytes = {
        0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde, 0xf0, 0x12,
        0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa,
        0xbb, 0xcc, 0xdd, 0xee, 0xff, 0x00, 0x11, 0x22,
        0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a
    };
    
    // Create private keys from raw bytes
    PrivateKey sk1 = PrivateKey::FromBytes(Bytes(sk1_bytes));
    PrivateKey sk2 = PrivateKey::FromBytes(Bytes(sk2_bytes));
    PrivateKey sk3 = PrivateKey::FromBytes(Bytes(sk3_bytes));
    
    // Get public keys
    G1Element pk1 = sk1.GetG1Element();
    G1Element pk2 = sk2.GetG1Element();
    G1Element pk3 = sk3.GetG1Element();
    
    // Message to sign
    vector<uint8_t> message = {0x74, 0x65, 0x73, 0x74, 0x20, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65}; // "test message"
    
    // Generate signatures
    G2Element sig1 = BasicSchemeMPL().Sign(sk1, message);
    G2Element sig2 = BasicSchemeMPL().Sign(sk2, message);
    G2Element sig3 = BasicSchemeMPL().Sign(sk3, message);
    
    // Print test vectors
    cout << "#[test]" << endl;
    cout << "fn test_full_c_compatibility() {" << endl;
    cout << "    use blsful::*;" << endl;
    cout << "    use subtle::CtOption;" << endl;
    cout << endl;
    cout << "    // Private keys (big-endian)" << endl;
    printHexArray("SK1_BYTES", sk1_bytes);
    printHexArray("SK2_BYTES", sk2_bytes);
    printHexArray("SK3_BYTES", sk3_bytes);
    
    cout << endl << "    // Expected public keys" << endl;
    printHexArray("EXPECTED_PK1", pk1.Serialize());
    printHexArray("EXPECTED_PK2", pk2.Serialize());
    printHexArray("EXPECTED_PK3", pk3.Serialize());
    
    cout << endl << "    // Message" << endl;
    printHexArray("MESSAGE", message);
    
    cout << endl << "    // Individual signatures" << endl;
    printHexArray("EXPECTED_SIG1", sig1.Serialize());
    printHexArray("EXPECTED_SIG2", sig2.Serialize());
    printHexArray("EXPECTED_SIG3", sig3.Serialize());
    
    // Normal aggregation
    G2Element normalAgg = BasicSchemeMPL().Aggregate({sig1, sig2, sig3});
    cout << endl << "    // Normal aggregation (without coefficients)" << endl;
    printHexArray("EXPECTED_NORMAL_AGG", normalAgg.Serialize());
    
    // Secure aggregation using helper class
    TestCoreMPL testCore;
    vector<G1Element> pks = {pk1, pk2, pk3};
    vector<G2Element> sigs = {sig1, sig2, sig3};
    G2Element secureAgg = testCore.AggregateSecure(pks, sigs, message, false);
    
    cout << endl << "    // Secure aggregation (with coefficients)" << endl;
    printHexArray("EXPECTED_SECURE_AGG", secureAgg.Serialize());
    
    // Verify results
    bool normalVerify = BasicSchemeMPL().AggregateVerify(pks, {message, message, message}, normalAgg);
    bool secureVerify = testCore.VerifySecure(pks, secureAgg, message, false);
    
    cout << endl << "    // Verification results" << endl;
    cout << "    const NORMAL_VERIFY_RESULT: bool = " << (normalVerify ? "true" : "false") << ";" << endl;
    cout << "    const SECURE_VERIFY_RESULT: bool = " << (secureVerify ? "true" : "false") << ";" << endl;
    
    cout << endl << "    // Test implementation..." << endl;
    cout << "    // (Rust test code will go here)" << endl;
    cout << "}" << endl;
    
    return 0;
}