// Cross-compatibility test program for C++/Rust BLS signature interoperability
// Generates keys, signatures, and secure aggregations that can be imported by Rust

#include <iostream>
#include <iomanip>
#include <vector>
#include <string>
#include "bls.hpp"
#include "schemes.hpp"
#include "util.hpp"
#include "elements.hpp"

using namespace bls;
using namespace std;

// Named constants for deterministic key generation seeds
const uint8_t SEED1_VALUE = 42;
const uint8_t SEED2_VALUE = 100;
const uint8_t SEED3_VALUE = 200;

void printHexBytes(const string& label, const vector<uint8_t>& data) {
    cout << label << " = [";
    for (size_t i = 0; i < data.size(); i++) {
        if (i > 0) cout << ", ";
        cout << "0x" << setfill('0') << setw(2) << hex << (int)data[i];
    }
    cout << "];" << endl;
}

void printRustTest(const string& test_name, 
                   const vector<PrivateKey>& sks,
                   const vector<G1Element>& pks,
                   const vector<G2Element>& sigs,
                   const vector<uint8_t>& message) {
    cout << "\n#[test]" << endl;
    cout << "fn " << test_name << "() {" << endl;
    cout << "    // Keys and signatures generated by C++ bls-signatures" << endl;
    cout << "    " << endl;
    
    // Export private keys
    cout << "    // Private keys from C++" << endl;
    for (size_t i = 0; i < sks.size(); i++) {
        auto skBytes = sks[i].Serialize();
        printHexBytes("    let cpp_sk" + to_string(i+1) + "_bytes", skBytes);
    }
    
    // Export public keys  
    cout << "\n    // Public keys from C++" << endl;
    for (size_t i = 0; i < pks.size(); i++) {
        auto pkBytes = pks[i].Serialize();
        printHexBytes("    let cpp_pk" + to_string(i+1) + "_bytes", pkBytes);
    }
    
    // Export individual signatures
    cout << "\n    // Individual signatures from C++" << endl;
    for (size_t i = 0; i < sigs.size(); i++) {
        auto sigBytes = sigs[i].Serialize();
        printHexBytes("    let cpp_sig" + to_string(i+1) + "_bytes", sigBytes);
    }
    
    // Export message
    cout << "\n    // Message" << endl;
    printHexBytes("    let message", message);
    
    cout << "\n    // Import C++ keys into Rust" << endl;
    for (size_t i = 0; i < sks.size(); i++) {
        cout << "    let sk" << (i+1) << " = SecretKey::<Bls12381G1Impl>::try_from(cpp_sk" << (i+1) << "_bytes.as_slice()).unwrap();" << endl;
        cout << "    let pk" << (i+1) << " = PublicKey::<Bls12381G1Impl>::try_from(cpp_pk" << (i+1) << "_bytes.as_slice()).unwrap();" << endl;
        cout << "    let sig" << (i+1) << " = Signature::<Bls12381G1Impl>::try_from(cpp_sig" << (i+1) << "_bytes.as_slice()).unwrap();" << endl;
    }
    
    cout << "\n    // Verify C++ signatures in Rust" << endl;
    for (size_t i = 0; i < sks.size(); i++) {
        cout << "    assert!(sig" << (i+1) << ".verify(&pk" << (i+1) << ", &message).is_ok());" << endl;
    }
    
    cout << "\n    // Test secure aggregation with C++ keys in Rust" << endl;
    cout << "    let signatures = vec![";
    for (size_t i = 0; i < sigs.size(); i++) {
        if (i > 0) cout << ", ";
        cout << "sig" << (i+1);
    }
    cout << "];" << endl;
    
    cout << "    let public_keys = vec![";
    for (size_t i = 0; i < pks.size(); i++) {
        if (i > 0) cout << ", ";
        cout << "pk" << (i+1);
    }
    cout << "];" << endl;
    
    cout << "\n    // Create secure aggregation in Rust using C++ keys" << endl;
    cout << "    let secure_agg = AggregateSignature::from_signatures_secure(&signatures, &public_keys).unwrap();" << endl;
    cout << "    let final_sig = match secure_agg {" << endl;
    cout << "        AggregateSignature::Basic(sig) => Signature::Basic(sig)," << endl;
    cout << "        _ => panic!(\"Expected Basic scheme\")," << endl;
    cout << "    };" << endl;
    
    cout << "\n    // Verify secure aggregation" << endl;
    cout << "    assert!(final_sig.verify_secure(&public_keys, &message).is_ok());" << endl;
    cout << "}" << endl;
}

int main() {
    cout << "// Cross-Compatibility Test Vectors" << endl;
    cout << "// Generated by C++ bls-signatures for import into Rust" << endl;
    cout << "use blsful::{AggregateSignature, PublicKey, SecretKey, Signature, Bls12381G1Impl};" << endl;
    cout << "" << endl;
    
    // Test Case 1: Two signers
    cout << "\n// === Test Case 1: Two Signers ===" << endl;
    
    vector<PrivateKey> sks2;
    vector<G1Element> pks2;
    vector<G2Element> sigs2;
    
    // Create deterministic keys using different seeds
    vector<uint8_t> seed1(32, SEED1_VALUE);
    vector<uint8_t> seed2(32, SEED2_VALUE);
    
    PrivateKey sk1 = BasicSchemeMPL().KeyGen(seed1);
    PrivateKey sk2 = BasicSchemeMPL().KeyGen(seed2);
    
    sks2.push_back(sk1);
    sks2.push_back(sk2);
    
    pks2.push_back(sk1.GetG1Element());
    pks2.push_back(sk2.GetG1Element());
    
    vector<uint8_t> message = {0x68, 0x65, 0x6c, 0x6c, 0x6f}; // "hello"
    
    // Sign with each key
    sigs2.push_back(BasicSchemeMPL().Sign(sk1, message));
    sigs2.push_back(BasicSchemeMPL().Sign(sk2, message));
    
    printRustTest("test_cpp_rust_two_signers", sks2, pks2, sigs2, message);
    
    // Test Case 2: Three signers
    cout << "\n// === Test Case 2: Three Signers ===" << endl;
    
    vector<PrivateKey> sks3;
    vector<G1Element> pks3;
    vector<G2Element> sigs3;
    
    vector<uint8_t> seed3(32, SEED3_VALUE);
    PrivateKey sk3 = BasicSchemeMPL().KeyGen(seed3);
    
    sks3.push_back(sk1);
    sks3.push_back(sk2);
    sks3.push_back(sk3);
    
    pks3.push_back(sk1.GetG1Element());
    pks3.push_back(sk2.GetG1Element());
    pks3.push_back(sk3.GetG1Element());
    
    sigs3.push_back(BasicSchemeMPL().Sign(sk1, message));
    sigs3.push_back(BasicSchemeMPL().Sign(sk2, message));
    sigs3.push_back(BasicSchemeMPL().Sign(sk3, message));
    
    printRustTest("test_cpp_rust_three_signers", sks3, pks3, sigs3, message);
    
    // Test normal aggregation for comparison
    cout << "\n// === Test Normal Aggregation (should fail verify_secure) ===" << endl;
    G2Element normalAgg = BasicSchemeMPL().Aggregate(sigs2);
    auto normalAggBytes = normalAgg.Serialize();
    
    cout << "\n#[test]" << endl;
    cout << "fn test_normal_aggregation_fails_secure_verify() {" << endl;
    printHexBytes("    let normal_agg_bytes", normalAggBytes);
    cout << "    " << endl;
    cout << "    // This normal aggregation should fail verify_secure" << endl;
    cout << "    let normal_sig = Signature::<Bls12381G1Impl>::try_from(normal_agg_bytes.as_slice()).unwrap();" << endl;
    cout << "    " << endl;
    cout << "    // Import the public keys from test case 1" << endl;
    printHexBytes("    let cpp_pk1_bytes", pks2[0].Serialize());
    printHexBytes("    let cpp_pk2_bytes", pks2[1].Serialize());
    cout << "    let pk1 = PublicKey::<Bls12381G1Impl>::try_from(cpp_pk1_bytes.as_slice()).unwrap();" << endl;
    cout << "    let pk2 = PublicKey::<Bls12381G1Impl>::try_from(cpp_pk2_bytes.as_slice()).unwrap();" << endl;
    cout << "    " << endl;
    printHexBytes("    let message", message);
    cout << "    " << endl;
    cout << "    // Normal aggregation should fail verify_secure" << endl;
    cout << "    assert!(normal_sig.verify_secure(&[pk1, pk2], &message).is_err());" << endl;
    cout << "}" << endl;
    
    return 0;
}