name:  Build and Test C++, Javascript, and Python

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ (github.ref == 'refs/heads/main') && github.sha || '' }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: ${{ matrix.os }} (Python ${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: ${{ matrix.python }}

    - name: Prepare build system for Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -qq --yes valgrind snap libgmp-dev libsodium-dev
        sudo apt-get remove --purge cmake -y
        sudo snap install cmake --classic
        hash -r
        cmake --version

    - name: Prepare build system for macOS
      if: startsWith(matrix.os, 'macos')
      run: |
        ls -l
        export MACOSX_DEPLOYMENT_TARGET=10.14

    - name: Build library using CMake
      run: |
        mkdir -p build
        ls -l build
        cd build
        cmake ../
        cmake --build . -- -j 6

    - name: Run tests with CMake build
      run: |
        cd build
        echo "Running ./src/runtest"
        ./src/runtest

    - name: Run valgrind on Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: cd build && valgrind --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=all  ./src/runtest

    - name: Test pure Python implementation
      run: |
        python python-impl/impl-test.py

    - name: Install emsdk
      uses: mymindstorm/setup-emsdk@v11

    - name: Test JavaScript bindings
      run: |
        emcc -v
        sh emsdk_build.sh
        sh js_test.sh

    - uses: actions/setup-go@v2
      with:
        go-version: "^1.17"

    - name: Test Go bindings
      run: |
        cd go-bindings
        make
